function compact(value = '') {
  return String(value || '')
    .replace(/주식회사|\(주\)|㈜|（주）/g, '')
    .replace(/[\s._\-()（）\[\]{}·ㆍ,:：/\\]+/g, '')
    .toLowerCase();
}

function toUpperText(...values) {
  return values.filter(Boolean).map((value) => String(value)).join(' ').toUpperCase();
}

function detectTemplateKind(mappingJson = {}, template = {}) {
  const raw = toUpperText(
    mappingJson.template_type,
    mappingJson.templateType,
    mappingJson.layout,
    mappingJson.layoutType,
    mappingJson.documentKind,
    template.template_type,
    template.templateType,
    template.template_name,
    template.templateName,
    template.template_code,
    template.templateCode,
    template.description
  );
  const ko = compact([
    mappingJson.title,
    mappingJson.name,
    mappingJson.sheetName,
    mappingJson.sheet,
    template.template_name,
    template.templateName,
    template.description,
  ].filter(Boolean).join(' '));

  if (raw.includes('CUSTOM_DOCUMENT_FORM') || raw.includes('DOCUMENT_FORM') || /문서양식|회사양식|결재양식/.test(ko)) return 'CUSTOM_DOCUMENT_FORM';
  if (raw.includes('MEETING') || /회의록|회의|안건|결정사항|조치사항/.test(ko)) return 'MEETING_MINUTES';
  if (raw.includes('OFFICIAL') || /공문|수신|참조|발신|시행/.test(ko)) return 'OFFICIAL_LETTER';
  if (raw.includes('REPORT') || raw.includes('SECTION') || raw.includes('APPROVAL') || /보고서|보고|검토|현황|리포트/.test(ko)) return 'REPORT';
  if (raw.includes('COMPARISON') || raw.includes('VENDOR') || /비교|업체별|회사별|거래처별/.test(ko)) return 'COMPARISON_MATRIX';
  if (raw.includes('ESTIMATE') || /견적/.test(ko)) return 'ESTIMATE';
  if (raw.includes('UNIT_PRICE') || raw.includes('PRICE') || /단가표|가격표|표준시장단가|단가/.test(ko)) return 'UNIT_PRICE_TABLE';
  if (raw.includes('WORK_LOG') || /작업일보|일보|투입인원|작업내용/.test(ko)) return 'WORK_LOG_TABLE';
  return 'NORMAL_TABLE';
}

function mapping(fieldKey, label, sourcePath, fallbackPaths = [], extra = {}) {
  return {
    fieldKey,
    label,
    mappingType: 'AUTO_VALUE',
    sourcePath,
    fallbackPaths,
    autoGenerated: true,
    ...extra,
  };
}

const COMMON_HEADER_MAPPINGS = [
  mapping('document_title', '문서명', 'rows.0.document_title', ['analysis.documentTitle', 'analysis.title', 'job.title', 'job.userRequest', 'mapping.title']),
  mapping('document_date', '작성일', 'rows.0.document_date', ['analysis.documentDate', 'analysis.date', 'today']),
  mapping('requester_name', '작성자', 'rows.0.requester_name', ['authorName', 'job.userName']),
  mapping('project_name', '공사명', 'rows.0.project_name', ['analysis.projectName', 'analysis.raw.projectName', 'keyValues.project_name']),
  mapping('site_name', '현장명', 'rows.0.site_name', ['analysis.siteName', 'analysis.raw.siteName', 'keyValues.site_name']),
  mapping('summary', '요약', 'rows.0.summary', ['analysis.summary', 'analysis.raw.summary']),
  mapping('remark', '비고', 'rows.0.remark', ['analysis.reviewSummary', 'job.userRequest']),
];

const PRESETS = {

  CUSTOM_DOCUMENT_FORM: {
    template_type: 'CUSTOM_DOCUMENT_FORM',
    layout: 'CUSTOM_DOCUMENT_FORM',
    sheetName: 'AI문서양식',
    title: 'AI 생성 문서 양식',
    sections: [
      { key: 'purpose', title: '1. 작성 목적', bindingKey: 'purpose', height: 3 },
      { key: 'summary', title: '2. 주요 내용', bindingKey: 'summary', height: 4 },
      { key: 'review', title: '3. 검토 의견', bindingKey: 'review_opinion', height: 4 },
      { key: 'action', title: '4. 후속 조치', bindingKey: 'action_plan', height: 3 },
    ],
    headerPairs: [
      { label: '작성일', bindingKey: 'document_date' },
      { label: '작성자', bindingKey: 'requester_name' },
      { label: '공사명', bindingKey: 'project_name' },
      { label: '현장명', bindingKey: 'site_name' },
    ],
    approvalLines: ['담당', '검토', '승인'],
    mappings: COMMON_HEADER_MAPPINGS,
  },
  REPORT: {
    template_type: 'REPORT',
    layout: 'SECTION_REPORT',
    sheetName: '보고서',
    title: '보고서 양식 v1',
    sections: [
      { key: 'report_purpose', label: '1. 보고 목적', type: 'textarea', order: 1 },
      { key: 'summary', label: '2. 주요 검토 내용', type: 'textarea', order: 2 },
      { key: 'issue_summary', label: '3. 주요 이슈 및 확인사항', type: 'textarea', order: 3 },
      { key: 'action_plan', label: '4. 조치 계획', type: 'textarea', order: 4 },
      { key: 'footer_note', label: '보고서 하단 메모', type: 'textarea', order: 5 },
    ],
    mappings: [
      mapping('report_title', '보고서 제목', 'rows.0.report_title', ['rows.0.document_title', 'analysis.documentTitle', 'analysis.title', 'mapping.title', 'job.title']),
      mapping('report_purpose', '보고 목적', 'rows.0.report_purpose', ['rows.0.purpose', 'analysis.purpose', 'analysis.documentPurpose', 'job.userRequest', 'analysis.summary']),
      mapping('summary', '주요 검토 내용', 'rows.0.summary', ['rows.0.content', 'analysis.summary', 'analysis.raw.summary', 'analysis.fileProfilesText', 'sourceText']),
      mapping('issue_summary', '주요 이슈 및 확인사항', 'rows.0.issue_summary', ['rows.0.review_opinion', 'analysis.reportDraft.issue_summary', 'analysis.drafts.report.issue_summary', 'issuesSummary']),
      mapping('action_plan', '조치 계획', 'rows.0.action_plan', ['analysis.actionPlan', 'analysis.nextSteps', 'analysis.raw.actionPlan', 'issuesActionPlan']),
      mapping('footer_note', '보고서 하단 메모', 'rows.0.footer_note', ['analysis.memo', 'job.userRequest']),
    ],
  },
  MEETING_MINUTES: {
    template_type: 'MEETING_MINUTES',
    layout: 'MEETING_ACTION_TABLE',
    sheetName: '회의록',
    title: '회의록 양식 v1',
    sections: [
      { key: 'agenda', label: '1. 회의 안건', type: 'textarea', order: 1 },
      { key: 'discussion', label: '2. 주요 논의 내용', type: 'textarea', order: 2 },
      { key: 'decision', label: '3. 결정 사항', type: 'textarea', order: 3 },
      { key: 'action_item', label: '4. 조치 사항', type: 'textarea', order: 4 },
    ],
    mappings: [
      mapping('meeting_title', '회의록 제목', 'rows.0.meeting_title', ['rows.0.document_title', 'analysis.documentTitle', 'mapping.title', 'job.title']),
      mapping('meeting_date', '회의일자', 'rows.0.meeting_date', ['analysis.documentDate', 'today']),
      mapping('attendees', '참석자', 'rows.0.attendees', ['analysis.attendees', 'keyValues.attendees']),
      mapping('agenda', '회의 안건', 'rows.0.agenda', ['analysis.purpose', 'job.userRequest', 'analysis.summary']),
      mapping('discussion', '주요 논의 내용', 'rows.0.discussion', ['analysis.summary', 'rows.0.content']),
      mapping('decision', '결정 사항', 'rows.0.decision', ['analysis.reviewSummary', 'analysis.summary']),
      mapping('action_item', '조치 사항', 'rows.0.action_item', ['analysis.drafts.meeting.action_items.0.action_item', 'analysis.meetingDraft.action_items.0.action_item', 'issuesActionPlan']),
    ],
  },
  OFFICIAL_LETTER: {
    template_type: 'OFFICIAL_LETTER',
    layout: 'OFFICIAL_LETTER',
    sheetName: '공문',
    title: '공문 양식 v1',
    mappings: [
      mapping('letter_title', '공문 제목', 'rows.0.letter_title', ['mapping.title', 'job.title']),
      mapping('document_no', '문서번호', 'rows.0.document_no', ['analysis.documentNo', 'keyValues.document_no']),
      mapping('recipient', '수신', 'rows.0.recipient', ['analysis.recipient', 'keyValues.recipient']),
      mapping('reference', '참조', 'rows.0.reference', ['analysis.reference', 'keyValues.reference']),
      mapping('document_title', '제목', 'rows.0.document_title', ['analysis.documentTitle', 'analysis.title', 'job.userRequest', 'job.title']),
      mapping('body', '본문', 'rows.0.body', ['rows.0.content', 'analysis.summary', 'analysis.purpose', 'sourceText']),
      mapping('attachment_note', '붙임', 'rows.0.attachment_note', ['analysis.attachmentNote']),
      mapping('sender', '발신', 'rows.0.sender', ['authorName', 'job.userName']),
    ],
  },
  ESTIMATE: {
    template_type: 'ESTIMATE',
    layout: 'ESTIMATE_FORM',
    sheetName: '견적서',
    title: '견적서 양식 v1',
    baseColumns: [
      { fieldKey: 'row_no', label: 'NO' }, { fieldKey: 'item_name', label: '품명' }, { fieldKey: 'spec', label: '규격' },
      { fieldKey: 'quantity', label: '수량' }, { fieldKey: 'unit', label: '단위' }, { fieldKey: 'unit_price', label: '단가' },
      { fieldKey: 'amount', label: '금액' }, { fieldKey: 'remark', label: '비고' },
    ],
    mappings: COMMON_HEADER_MAPPINGS,
  },
  UNIT_PRICE_TABLE: {
    template_type: 'UNIT_PRICE_TABLE',
    layout: 'PRICE_TABLE',
    sheetName: '단가표',
    title: '단가표 양식 v1',
    baseColumns: [
      { fieldKey: 'row_no', label: 'NO' }, { fieldKey: 'construction_code', label: '공종코드' }, { fieldKey: 'item_name', label: '공종명/품명' },
      { fieldKey: 'spec', label: '규격' }, { fieldKey: 'unit', label: '단위' }, { fieldKey: 'quantity', label: '수량' },
      { fieldKey: 'unit_price', label: '단가' }, { fieldKey: 'amount', label: '금액' }, { fieldKey: 'remark', label: '비고' },
    ],
    mappings: COMMON_HEADER_MAPPINGS,
  },
  COMPARISON_MATRIX: {
    template_type: 'COMPARISON_MATRIX',
    layout: 'AI_GENERATED_DYNAMIC_VENDOR_TABLE',
    sheetName: '비교표',
    title: '업체별 단가 비교표',
    baseColumns: [
      { fieldKey: 'row_no', label: 'NO' }, { fieldKey: 'item_name', label: '품명' }, { fieldKey: 'spec', label: '규격' },
      { fieldKey: 'quantity', label: '수량' }, { fieldKey: 'unit', label: '단위' },
    ],
    repeatGroups: [{ groupKey: 'vendors', repeatBy: 'vendor', columns: [{ fieldKey: 'unit_price', label: '단가' }, { fieldKey: 'amount', label: '금액' }] }],
    summaryColumns: [{ fieldKey: 'lowest_target', label: '최저 업체' }, { fieldKey: 'calculated_unit_price', label: '최저 단가' }, { fieldKey: 'remark', label: '비고' }],
    mappings: COMMON_HEADER_MAPPINGS,
  },
  WORK_LOG_TABLE: {
    template_type: 'WORK_LOG_TABLE',
    layout: 'WORK_LOG_TABLE',
    sheetName: '작업일보',
    title: '작업일보 양식 v1',
    baseColumns: [
      { fieldKey: 'row_no', label: 'NO' }, { fieldKey: 'work_date', label: '작업일자' }, { fieldKey: 'work_content', label: '작업내용' },
      { fieldKey: 'worker_count', label: '투입인원' }, { fieldKey: 'equipment_name', label: '장비명' }, { fieldKey: 'remark', label: '비고' },
    ],
    mappings: COMMON_HEADER_MAPPINGS,
  },
  NORMAL_TABLE: {
    template_type: 'NORMAL_TABLE',
    layout: 'TABLE_ONLY',
    sheetName: '일반내역표',
    title: '데이터 정리표',
    baseColumns: [
      { fieldKey: 'row_no', label: 'NO' }, { fieldKey: 'item_name', label: '품명' }, { fieldKey: 'spec', label: '규격' },
      { fieldKey: 'quantity', label: '수량' }, { fieldKey: 'unit', label: '단위' }, { fieldKey: 'unit_price', label: '단가' },
      { fieldKey: 'amount', label: '금액' }, { fieldKey: 'remark', label: '비고' },
    ],
    mappings: COMMON_HEADER_MAPPINGS,
  },
};

function mergeMappings(existing = [], additions = []) {
  const out = Array.isArray(existing) ? existing.filter(Boolean) : [];
  const seen = new Set(out.map((item) => String(item.fieldKey || item.field_key || '').trim()).filter(Boolean));
  additions.forEach((item) => {
    const key = String(item.fieldKey || item.field_key || '').trim();
    if (!key || seen.has(key)) return;
    seen.add(key);
    out.push(item);
  });
  return out;
}

function ensureTemplateMappingJson(mappingJson = {}, template = {}) {
  const base = mappingJson && typeof mappingJson === 'object' ? { ...mappingJson } : {};
  const kind = detectTemplateKind(base, template);
  const preset = PRESETS[kind] || PRESETS.NORMAL_TABLE;
  const out = {
    ...preset,
    ...base,
    template_type: base.template_type || base.templateType || preset.template_type,
    sheetName: base.sheetName || base.sheet || template.default_sheet_name || template.defaultSheetName || preset.sheetName,
    layout: base.layout || base.layoutType || preset.layout,
    title: base.title || template.template_name || template.templateName || preset.title,
    autoMappingVersion: '2026-06-24-v2',
    autoValueFallback: true,
  };
  out.sections = Array.isArray(base.sections) && base.sections.length ? base.sections : (preset.sections || []);
  out.headerPairs = Array.isArray(base.headerPairs) && base.headerPairs.length ? base.headerPairs : (preset.headerPairs || []);
  out.approvalLines = Array.isArray(base.approvalLines) && base.approvalLines.length ? base.approvalLines : (preset.approvalLines || []);
  out.baseColumns = Array.isArray(base.baseColumns) && base.baseColumns.length ? base.baseColumns : (preset.baseColumns || []);
  out.repeatGroups = Array.isArray(base.repeatGroups) && base.repeatGroups.length ? base.repeatGroups : (preset.repeatGroups || []);
  out.summaryColumns = Array.isArray(base.summaryColumns) && base.summaryColumns.length ? base.summaryColumns : (preset.summaryColumns || []);
  out.mappings = mergeMappings(base.mappings, preset.mappings || []);
  if (!out.mappings.length && COMMON_HEADER_MAPPINGS.length) out.mappings = [...COMMON_HEADER_MAPPINGS];
  return out;
}

function hasRealExcelCellMapping(mappingJson = {}) {
  const mappings = Array.isArray(mappingJson.mappings) ? mappingJson.mappings : [];
  return mappings.some((m) => m && (
    m.cellAddress || m.mergedRange || m.columnLetter ||
    (Array.isArray(m.columnLetters) && m.columnLetters.length) ||
    (Array.isArray(m.groupRanges) && m.groupRanges.length)
  ));
}

module.exports = {
  ensureTemplateMappingJson,
  detectTemplateKind,
  hasRealExcelCellMapping,
};
